apiVersion: v1
kind: ConfigMap
metadata:
  name: sre-common-config
  namespace: sre-project
data:
  PRODUCT_SERVICE_URL: "http://product-service:3002"
  PAYMENT_SERVICE_URL: "http://payment-service:3004"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  ORDER_SERVICE_URL: "http://order-service:3003"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3005"
  USER_PROFILE_SERVICE_URL: "http://user-profile-service:3006"
  DATABASE_URL: "postgres://sre_user:sre_password@postgres:5432/sre_db"

